/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.gooddata.oauth2.server

// TODO remove after real classes are added
class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
