default:
  image: adoptopenjdk/openjdk11:$BUILD_IMAGE_VERSION
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  BUILD_IMAGE_VERSION: "x86_64-debianslim-jdk-11.0.10_9"
stages:
  - build
  - test
  - release
build-kotlin:
  stage: build
  cache:
    key: kotlin-build
    paths:
      - .gradle
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew clean build compileTestKotlin -x test --info
  artifacts:
    paths:
      - '**/build/**/*'
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
test-kotlin:
  stage: test
  cache:
    key: kotlin-build
    policy: pull
    paths:
      - .gradle
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew test --info
  dependencies:
    - build-kotlin
  artifacts:
    reports:
      junit: '**/build/test-results/**/TEST-*.xml'
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
build-and-publish-library:
  stage: release
  dependencies: []
  cache:
    key: kotlin-build
    paths:
      - .gradle
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    # only publish to GitLab package registry is done, release is performed on Jenkins
    - ./gradlew clean publishLibraryPublicationToGitlabMavenRepository --info
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
