default:
  image: adoptopenjdk/openjdk11:$BUILD_IMAGE_VERSION
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  BUILD_IMAGE_VERSION: "x86_64-debianslim-jdk-11.0.10_9"
  AWS_ECR_URL: '441851189095.dkr.ecr.eu-central-1.amazonaws.com'
stages:
  - compliance-check
  - build
  - test
  - release
compliance-check:
  image: $AWS_ECR_URL/infra/compliance-check:latest
  stage: compliance-check
  dependencies: []
  variables:
    GIT_STRATEGY: none
    GITLAB_API_PRIVATE_TOKEN: $COMPLIANCE_CHECK_TOKEN
  before_script: []
  script:
    - echo "Running compliance check in enforcing mode..."
    - /scripts/gitlab.sh
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
build-kotlin:
  stage: build
  cache:
    key: kotlin-build
    paths:
      - .gradle
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew clean build compileTestKotlin -x test --info
  artifacts:
    paths:
      - '**/build/**/*'
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
test-kotlin:
  stage: test
  cache:
    key: kotlin-build
    policy: pull
    paths:
      - .gradle
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew test --info
  dependencies:
    - build-kotlin
  artifacts:
    reports:
      junit: '**/build/test-results/**/TEST-*.xml'
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
build-and-publish-library:
  stage: release
  dependencies: []
  cache:
    key: kotlin-build
    paths:
      - .gradle
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    # publish to GitLab package registry is done, a corresponding tag needs to be created beforehand
    - ./gradlew clean publishLibraryPublicationToGitlabMavenRepository -Prelease_version=${CI_COMMIT_TAG#*gooddata-server-oauth2-} --info
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
