---

on:
  push:
    tags:
      - "gooddata-server-oauth2-*.*.*"
      - "*.*.*"

jobs:
  ###########################
  #  BUILD & PUBLISH STAGE
  ###########################
  test-kotlin:
    runs-on: infra1-medium
    steps:
      - uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v3
        with:
          key: kotlin-build
          path: .gradle
      - name: Get Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Publish to Nexus and to GitLab with Gradle Wrapper
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GITLAB_PACKAGES_UPLOAD_TOKEN: ${{ secrets.GITLAB_PACKAGES_UPLOAD_TOKEN }}
        run: |
          ./gradlew clean publish -Pversion=$TAG_NAME --info
