---

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  ###########################
  #  BUILD & PUBLISH STAGE
  ###########################
  release-library-kotlin:
    runs-on: infra1-medium
    steps:
      - uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v3
        with:
          key: kotlin-build
          path: .gradle
      - name: Publish to Nexus with Gradle Wrapper
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GITLAB_PACKAGES_UPLOAD_TOKEN: ${{ secrets.GITLAB_PACKAGES_UPLOAD_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "$VERSION" | grep -P '^\d+\.\d+\.\d+$'
          git tag $VERSION
          git push origin $VERSION
          ./gradlew clean publish -Pversion=$VERSION --info
